# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-04"

[[extensions]]
name = "checkout-rewards-ui"
handle = "checkout-rewards-ui"
type = "ui_extension"


# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
target = "purchase.checkout.reductions.render-after"
module = "./src/Checkout.jsx"
export = "checkoutRender"

[[extensions.targeting]]
target = "purchase.thank-you.customer-information.render-after"
module = "./src/Checkout.jsx"
export = "thankYouRender"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields


[[extensions.metafields]]
namespace = "checkout_rewards"
key = "points"
type = "customer"
target = "customer"

[[extensions.metafields]]
namespace = "rewards"
key = "points"
type = "customer"
target = "customer"

[[extensions.metafields]]
namespace = "checkout_rewards"
key = "discount_code"
type = "shop"
target = "shop"

[[extensions.metafields]]
namespace = "checkout_rewards"
key = "percentage_value"
type = "shop"
target = "shop"

[[extensions.metafields]]
namespace = "checkout_rewards"
key = "points_required"
type = "shop"
target = "shop"


# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

# [extensions.settings]
# [[extensions.settings.fields]]
# key = "banner_title"
# type = "single_line_text_field"
# name = "Banner title"
# description = "Enter a title for the banner"
