import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://checkout-rewards-app.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Shop",
  fields: {
    checkoutRewardsDiscountCode: {
      type: "string",
      shopifyMetafield: {
        privateMetafield: false,
        namespace: "checkout_rewards",
        key: "discount_code",
        metafieldType: "single_line_text_field",
        allowMultipleEntries: false,
      },
      storageKey: "dpvMS3ETwNb9",
    },
    checkoutRewardsDiscountPercentageValue: {
      type: "string",
      shopifyMetafield: {
        privateMetafield: false,
        namespace: "checkout_rewards",
        key: "percentage_value",
        metafieldType: "number_integer",
        allowMultipleEntries: false,
      },
      storageKey: "FL3KSh1dtBJL",
    },
    checkoutRewardsPointsRequired: {
      type: "string",
      shopifyMetafield: {
        privateMetafield: false,
        namespace: "checkout_rewards",
        key: "points_required",
        metafieldType: "number_integer",
        allowMultipleEntries: false,
      },
      storageKey: "UdxJVCUgqFeM",
    },
  },
  shopify: {
    fields: [
      "address1",
      "address2",
      "billingAddresses",
      "cartLineItems",
      "carts",
      "checkoutApiSupported",
      "checkoutAppliedGiftCards",
      "checkoutLineItems",
      "checkoutShippingRates",
      "checkouts",
      "city",
      "country",
      "countryCode",
      "countryName",
      "countyTaxes",
      "currency",
      "customerAccountsV2",
      "customerEmail",
      "customers",
      "discounts",
      "domain",
      "eligibleForPayments",
      "email",
      "enabledPresentmentCurrencies",
      "finances",
      "gdprRequests",
      "googleAppsDomain",
      "googleAppsLoginEnabled",
      "hasDiscounts",
      "hasGiftCards",
      "hasStorefront",
      "ianaTimezone",
      "latitude",
      "longitude",
      "marketingSmsContentEnabledAtCheckout",
      "moneyFormat",
      "moneyInEmailsFormat",
      "moneyWithCurrencyFormat",
      "moneyWithCurrencyInEmailsFormat",
      "multiLocationEnabled",
      "myshopifyDomain",
      "name",
      "orderLineItems",
      "orders",
      "passwordEnabled",
      "phone",
      "plan",
      "planDisplayName",
      "planName",
      "preLaunchEnabled",
      "primaryLocale",
      "productVariants",
      "products",
      "province",
      "provinceCode",
      "requiresExtraPaymentsAgreement",
      "setupRequired",
      "shippingAddresses",
      "shopOwner",
      "shopifyCreatedAt",
      "shopifyUpdatedAt",
      "source",
      "syncs",
      "taxShipping",
      "taxesIncluded",
      "timezone",
      "transactionalSmsDisabled",
      "weightUnit",
      "zipCode",
    ],
  },
};
